### ISSUE TITLE
Datastore must be of type AzureBlobDatastore

### ISSUE THREAD

**Issue by guybartal** [microsoft/MLOps_VideoAnomalyDetection#2]
default datastore may be Azure Files so it breaks on "Schedule.create" which expects AzureBlobDatastore:

```
schedule = Schedule.create(workspace=ws, name=pipeline_name + "_sch",
                           pipeline_id=published_pipeline.id, 
                           experiment_name='prednet_master',
                           datastore=datastore,
                           wait_for_provisioning=True,
                           description="Datastore scheduler for Pipeline" + pipeline_name,
                           path_on_datastore='prednet/data/video',
                           polling_interval=1
                           )

```
error:
```
Uploaded 1 files
Traceback (most recent call last):
  File "pipelines_master.py", line 145, in <module>
    polling_interval=1
  File "/home/vsts/.local/lib/python3.6/site-packages/azureml/pipeline/core/schedule.py", line 363, in create
    raise ValueError('Datastore must be of type AzureBlobDatastore')
ValueError: Datastore must be of type AzureBlobDatastore
##[error]Script failed with error: Error: /bin/bash failed with return code: 1
```

**Comment by wmpauli** [comment]
Interesting. I cannot reproduce this problem. My default datastore is Bob. Would you say that defaults have changed for the default datastore?
